# å…·ä½“é…ç½®æ–‡æ¡£åœ°å€ https://github.com/lowlighter/metrics/blob/master/action.yml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: GitHub metrics
on:
  schedule: 
      - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.calendar.full.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_calendar: yes
         plugin_calendar_limit: 0
     
      - name: Labels
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
      # base metrics
      - name: base_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base_metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: SuperCB
          template: classic
          config_timezone: Asia/Shanghai
          committer_message: ":rocket: Update"
          base: "header, activity, community, repositories"
          plugin_traffic: yes
          plugin_lines: yes
      
      # plugin metrics
      - name: plugin_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: plugin_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: SuperCB
          template: classic
          committer_message: ":rocket: Update"
          base: ""
          config_timezone: Asia/Shanghai
          
          # ğŸ† Achievements æˆ‘çš„æˆå°±
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
  
          
          
                           
          
          # âœ¨ Stargazers over last weeks
          plugin_stargazers: yes

          
          # ğŸ’¡ Coding habits (ç¼–ç ä¹ æƒ¯)
          plugin_habits: yes
          plugin_habits_from: 200                                   # Use 200 events to compute habits
          plugin_habits_days: 14                                    # Keep only events from last 14 days
          plugin_habits_facts: yes                                  # Display facts section
          plugin_habits_charts: yes                                 # Display charts section
          plugin_habits_trim: yes                                   # Trim unused hours on daily chart
          
          # ğŸ§‘â€ğŸ¤â€ğŸ§‘ People plugin å…³æ³¨ä¸è¢«å…³æ³¨
          plugin_people: yes
          plugin_people_types: followers, following                 # Display followers and "thanks" sections
          plugin_people_limit: 150                                   # Limit to 28 entries per section
          plugin_people_size: 36                                    # Size in pixels of displayed avatars
          plugin_people_identicons: no                              # Use avatars (do not use identicons)
          plugin_people_thanks: octocat                             # Users that will be displayed in "thanks" section
          plugin_people_sponsors_custom: octocat                    # Users that will be displayed additionally in "sponsors" section
          plugin_people_shuffle: yes                                # Shuffle for varied output
          

         
         # ğŸŒŸ Recently starred repositories
          plugin_stars: yes
          plugin_stars_limit: 5   # Limit to 5 entries
         
 

